//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.dcc.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int AttendanceId { get; set; }
        public Nullable<System.DateTime> DateOfDate { get; set; }
        public Nullable<int> WorkerId { get; set; }
        public string DeptGroup { get; set; }
        public Nullable<bool> PresentAbsent { get; set; }
    
        public virtual Believer Believer { get; set; }
    }
}
