//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.dcc.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Due
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Due()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int DuesId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string DuesName { get; set; }
        public string DuesDesc { get; set; }
        public string DuesType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> DeptId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
