//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.dcc.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int MemberId { get; set; }
        public Nullable<int> BelieverId { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public string Status { get; set; }
        public string Groups { get; set; }
        public string ProbationStatus { get; set; }
        public string Post { get; set; }
    
        public virtual Believer Believer { get; set; }
        public virtual Department Department { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Post Post1 { get; set; }
    }
}
