//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.dcc.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public Nullable<int> DuesId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Month { get; set; }
        public string Year { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string ExpenseBy { get; set; }
        public string Narration { get; set; }
        public string AuthorizedBy { get; set; }
        public string TransactionType { get; set; }
        public Nullable<int> DeptId { get; set; }
        public string PaymentSatus { get; set; }
    
        public virtual Believer Believer { get; set; }
        public virtual Due Due { get; set; }
        public virtual Month Month1 { get; set; }
    }
}
