//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.dcc.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersAccount
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> BelieverId { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual Believer Believer { get; set; }
        public virtual Department Department { get; set; }
        public virtual Role Role { get; set; }
    }
}
